repos:
- repo: https://github.com/psf/black
  rev: 'refs/tags/26.3.0:refs/tags/26.3.0'
  hooks:
  - id: black
    files: ^megatron/core/.*|^tests/unit_tests/.*
    args: ["--skip-magic-trailing-comma", "--skip-string-normalization"]
- repo: https://github.com/pycqa/pylint
  rev: v3.2.6
  hooks:
  - id: pylint
    files: ^megatron/core/.*
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    files: ^megatron/core/.*
- repo: local
  hooks:
  - id: check-dco
    name: Check Signed-off-by trailer
    entry: bash -c 'if ! grep -q "Signed-off-by:" "$1"; then echo "❌ Commit message must be signed off. Use git commit -s to add it automatically."; exit 1; fi' --
    language: system
    always_run: true
    stages: [commit-msg]
    types: [text]
