ARG FROM_IMAGE_NAME=nvcr.io/nvidia/pytorch:23.04-py3
FROM ${FROM_IMAGE_NAME}

RUN pip install --no-cache-dir \
    "pytest-cov" \
    "pytest_mock" \
    "nltk" \
    "wrapt" \
    "zarr" \
    "tensorstore==0.1.45" \
    "git+https://github.com/fanshiqing/grouped_gemm@main" \
    "black==19.10b0" \
    "isort" \
    "click==8.0.2"
