# syntax=docker/dockerfile:experimental

FROM nvcr.io/nvidia/pytorch:24.01-py3
ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i -e 's/^APT/# APT/' -e 's/^DPkg/# DPkg/' \
      /etc/apt/apt.conf.d/docker-clean

RUN apt-get update && apt-get install -y --no-install-recommends

RUN pip3 install sentencepiece einops flask-restful pytest wandb
RUN pip3 install git+https://github.com/fanshiqing/grouped_gemm@v1.1.1