#!/bin/bash

#SBATCH -p gb200
#SBATCH -q normal
#SBATCH --account=coreai_dlalgo_llm
#SBATCH -J coreai_dlalgo_llm-dcp.perf
#SBATCH --ntasks-per-node=4
#SBATCH --nodes=64
#SBATCH --time=2:00:00
#SBATCH --exclusive
#SBATCH --mem=0
#SBATCH --dependency=singleton
#SBATCH --output=dcp_ultra_sft_%j.out


export NVTE_FWD_LAYERNORM_SM_MARGIN=16
export NVTE_BWD_LAYERNORM_SM_MARGIN=16 
export TORCHINDUCTOR_WORKER_START=fork
export QUANTIZATION_TYPE_DEBUG=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export OMP_NUM_THREADS=16

export HF_HOME="/lustre/fsw/coreai_dlalgo_llm/users/pmannan/hf_home"

NAME=${SLURM_JOB_NAME}

# OUTPUT_ROOT="/lustre/fs1/portfolios/llmservice/projects/llmservice_modelalignment_ppo/users/adithyare/nemotron_ultra/sft-runs"
MEGATRON_LM_DIR=/lustre/fsw/coreai_dlalgo_llm/users/pmannan/megatron-lm
IMAGE="/lustre/fsw/coreai_dlalgo_llm/users/guyueh/rl_projects/mxfp8_train/pt_ultra_mamba_ssmv230_23jan28.sqsh"

DATETIME=`date +'date_%y-%m-%d_time_%H-%M-%S'`
RUN_DIR="${MEGATRON_LM_DIR}/${DATETIME}"
mkdir -p ${RUN_DIR}
LOGS_DIR="${RUN_DIR}/logs/"
CHECKPOINT_DIR="${RUN_DIR}/checkpoints/"
DATACACHE_DIR="${RUN_DIR}/data_cache/"
TENSORBOARD_DIR="${RUN_DIR}/tensorboard/"

mkdir -p ${LOGS_DIR}
mkdir -p ${CHECKPOINT_DIR}
mkdir -p ${DATACACHE_DIR}
mkdir -p ${TENSORBOARD_DIR}

SEQ_LEN=131072
TRAIN_SAMPLES=10000
LR_WARMUP_SAMPLES=100
LR_DECAY_SAMPLES=$((TRAIN_SAMPLES-LR_WARMUP_SAMPLES))
LOG_INTERVAL=1
SAVE_INTERVAL=20
SAVE_RETAIN_INTERVAL=100
GBS=64
LR=1e-5
MIN_LR=2e-6

TOKENIZER_MODEL_PATH="/lustre/fsw/coreai_dlalgo_llm/users/guyueh/rl_projects/mxfp8_train/tokenizer"
# BASE_MODEL_PATH="/lustre/fs1/portfolios/llmservice/projects/llmservice_modelalignment_ppo/users/adithyare/nemotron_ultra/reinit-embeddings-ckpts/phase1_fp32rs_continued_iter_0600000/checkpoints"
BLEND_PATH="/lustre/fsw/coreai_dlalgo_llm/users/guyueh/rl_projects/mxfp8_train/blend_jan21.json"

WANDB_PROJECT="nemo-rl-sft-dev-guyueh"
WANDB_EXP_NAME="ultra-v3-sft-hsg-mainfeb5merge-mxfp8-fp8_param-8node"


srun --ntasks-per-node=4 \
--container-image=${IMAGE} \
--container-mounts="/lustre:/lustre" \
--output="${LOGS_DIR}/%x_%j_${DATETIME}.log" \
sh -c "python -u \
${MEGATRON_LM_DIR}/pretrain_mamba.py \
    --sft \
    --sft-tokenizer-prompt-format identity \
    --distributed-timeout-minutes 5 \
    --num-dataset-builder-threads 32 \
    --tokenizer-type SFTTokenizer \
    --tokenizer-model ${TOKENIZER_MODEL_PATH} \
    \
    --recompute-granularity selective \
    --recompute-modules moe \
    --mtp-use-repeated-layer \
    \
    --context-parallel-size 16 \
	--tensor-model-parallel-size 8 \
	--expert-model-parallel-size 128 \
    --expert-tensor-parallel-size 1 \
    --pipeline-model-parallel-size 1 \
	--hybrid-override-pattern MEMEMEM*EMEMEM*EMEMEMEM*EMEMEMEM*EMEMEM*EMEMEMEM*EMEMEMEM*EMEMEM*EMEMEMEM*EMEMEMEM*EMEMEM*EMEMEMEM*EMEMEMEME \
	--mtp-hybrid-override-pattern \"*E\" \
    \
    \
    --save-interval ${SAVE_INTERVAL} \
    --save-retain-interval ${SAVE_RETAIN_INTERVAL} \
    --lr $LR \
    --min-lr $MIN_LR \
    --lr-decay-style constant \
    --train-samples ${TRAIN_SAMPLES} \
    --lr-warmup-samples ${LR_WARMUP_SAMPLES} \
    --lr-decay-samples ${LR_DECAY_SAMPLES} \
    --seq-length ${SEQ_LEN} \
    --max-position-embeddings ${SEQ_LEN} \
    --log-interval ${LOG_INTERVAL} \
    --micro-batch-size 1 \
    --global-batch-size ${GBS} \
    --overlap-grad-reduce \
    --overlap-param-gather \
    \
    --mtp-num-layers 2 \
    --calculate-per-token-loss \
    --mtp-loss-scaling-factor 0.3 \
    \
	--cuda-graph-scope mamba attn moe_router \
    --te-rng-tracker \
    --high-priority-stream-groups ep \
    --manual-gc-interval 10 \
    --ddp-num-buckets 10 \
    --manual-gc \
    \
    --moe-latent-size 2048 \
    --moe-permute-fusion \
    --cross-entropy-loss-fusion \
    --cross-entropy-fusion-impl native \
    --use-fused-weighted-squared-relu \
    \
    --moe-token-dispatcher-type alltoall \
    --moe-router-score-function sigmoid \
    --moe-grouped-gemm \
	--num-experts 512 \
	--moe-router-topk 22 \
    --moe-aux-loss-coeff 1e-4 \
    --moe-router-topk-scaling-factor 5.0 \
    --moe-router-enable-expert-bias \
    --moe-router-dtype fp32 \
    --moe-router-load-balancing-type seq_aux_loss \
    --moe-shared-expert-intermediate-size 10240 \
    \
    --attention-backend flash \
    --num-workers 1 \
    --disable-gloo-process-groups \
    --ckpt-format torch_dist \
    --ckpt-fully-parallel-save \
    --ckpt-fully-parallel-load \
    --ckpt-assume-constant-structure \
    --use-persistent-ckpt-worker \
    \
    --squared-relu \
    --no-mmap-bin-files \
    --exit-duration-in-mins 5750 \
    --no-create-attention-mask-in-dataloader \
    \
    --sequence-parallel \
    --use-distributed-optimizer \
    --override-opt_param-scheduler \
    \
    --mamba-num-heads 256 \
    --is-hybrid-model \
    --untie-embeddings-and-output-weights \
    --init-method-std 0.014 \
    --position-embedding-type none \
        --num-layers 108 \
    --hidden-size 8192 \
    --num-attention-heads 64 \
    --group-query-attention \
    --num-query-groups 2 \
    --ffn-hidden-size 5120 \
    --kv-channels 128 \
    \
    \
    --per-split-data-args-path ${BLEND_PATH} \
    --data-cache-path ${DATACACHE_DIR} \
    --weight-decay 0.1 \
    --clip-grad 1.0 \
    --attention-dropout 0.0 \
    --hidden-dropout 0.0 \
    --disable-bias-linear \
    --normalization RMSNorm \
    --no-load-optim \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --log-params-norm \
    --log-num-zeros-in-grad \
    --log-throughput \
    --log-progress \
    --log-energy \
    --log-memory-interval 200 \
    --logging-level 20 \
    --log-straggler \
    --disable-straggler-on-startup \
    --straggler-minmax-count 16 \
    --check-weight-hash-across-dp-replicas-interval 20000 \
    --ddp-pad-buckets-for-high-nccl-busbw \
    --timing-log-option minmax \
    --eval-interval 1000 \
    --eval-iters 14 \
    --bf16 \
    --use-mcore-models \
    --spec megatron.core.models.mamba.mamba_layer_specs mamba_stack_spec \
    \
    --hybrid-context-parallel \
    --max-seqlen-per-dp-cp-rank 4096 \
    --rerun-mode disabled \
    \
    --dist-ckpt-strictness log_unexpected \
    --tensorboard-dir ${TENSORBOARD_DIR} \
	--fp8-format e4m3 \
	--fp8-recipe mxfp8 \
    --moe-router-fusion \
    "