#!/bin/bash

echo "=================================================================================="
echo "测试 micro_batch 控制功能"
echo "=================================================================================="

echo ""
echo "修改总结:"
echo "1. 将 control_iter 从控制 iteration 数量改为控制 micro_batch 数量"
echo "2. 移除了所有 sample 记录相关的代码"
echo "3. 在训练循环中添加了 micro_batch 计数和提前退出逻辑"
echo "4. 更新了所有相关的文档和帮助信息"
echo ""

echo "主要变化:"
echo "- TensorSaver 类现在使用 control_micro_batches 参数"
echo "- 移除了 sample_idx 相关的所有参数和方法"
echo "- 在 pipeline 训练循环中添加了 micro_batch 计数"
echo "- 当达到指定的 micro_batch 数量时会提前退出训练"
echo ""

echo "使用示例:"
echo "  # 收集1个micro_batch的数据（默认）"
echo "  ./run_tensor_collection.sh single mxfp8"
echo ""
echo "  # 收集3个micro_batch的数据，每个micro_batch大小为2"
echo "  ./run_tensor_collection.sh --mode single --quant-type mxfp8 --control-iter 3 --micro-batch-size 2"
echo ""
echo "  # 通过主脚本收集2个micro_batch的数据，每个micro_batch大小为1"
echo "  ./run_tensor_draw.sh --mode collect --quant-type mxfp8 --control-iter 2 --micro-batch-size 1"
echo ""

echo "=================================================================================="
echo "测试完成！"
echo "=================================================================================="
