# Transformer module -- foundational for models, inference, pipeline_parallel,
# distributed, and most other modules.  Changes here cascade widely.
test_buckets:
  - fp8_param
  - pipeline_parallel
  - models
  - ckpt_optimizer
  - ckpt
  - ckpt_models
  - ckpt_moe_experts
  - transformer
  - transformer_moe
  - distributed_fsdp
  - catch_all
