# Models module -- heavily uses transformer, tensor_parallel, fusions,
# dist_checkpointing, inference, ssm, extensions, quantization.
test_buckets:
  - fp8_param
  - pipeline_parallel
  - models
  - ckpt_optimizer
  - ckpt
  - ckpt_models
  - ckpt_moe_experts
  - transformer
  - transformer_moe
  - distributed_fsdp
  - catch_all
