# Copyright (C) 2024 Intel Corporation

from pathlib import Path
from unittest import mock

import pytest

#Failures on Titan XP GPU
list_of_skip = ("tests/unit_tests/dist_checkpointing/test_optimizer.py::TestDistributedOptimizer::test_dp_sharding[tp_pp0-2-2-False-initialize_small_model]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_allgather_dispatcher[8-1-1]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_allgather_dispatcher[4-2-1]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_allgather_dispatcher[1-1-8]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_allgather_dispatcher[2-1-4]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_allgather_dispatcher[2-2-2]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_a2a_dispatcher[8-1-1]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_a2a_dispatcher[4-2-1]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_a2a_dispatcher[1-1-8]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_a2a_dispatcher[2-1-4]",
                       "tests/unit_tests/transformer/moe/test_aux_loss.py::TestAuxLoss::test_a2a_dispatcher[2-2-2]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestDistributedOptimizer::test_dp_sharding[tp_pp0-2-2-False-initialize_gpt_model]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestDistributedOptimizer::test_dp_sharding[tp_pp0-2-2-True-initialize_small_model]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestDistributedOptimizer::test_dp_sharding[tp_pp0-2-2-True-initialize_gpt_model]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestDistributedOptimizer::test_finetune_doesnt_load_optimizer[src_tp_pp0-dest_tp_pp0-False]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestDistributedOptimizer::test_finetune_doesnt_load_optimizer[src_tp_pp1-dest_tp_pp1-True]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestDistributedOptimizer::test_finetune_doesnt_load_optimizer[src_tp_pp2-dest_tp_pp2-False]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestDistributedOptimizer::test_can_load_deprecated_bucket_space_format",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestFP32Optimizer::test_fp32_optimizer_resharding[src_tp_pp0-dest_tp_pp0]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestFP32Optimizer::test_fp32_optimizer_resharding[src_tp_pp1-dest_tp_pp1]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestFP32Optimizer::test_fp32_optimizer_resharding[src_tp_pp2-dest_tp_pp2]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestOptimizerResharding::test_optimizer_resharding[src_tp_pp0-dest_tp_pp0-True-True]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestOptimizerResharding::test_optimizer_resharding[src_tp_pp1-dest_tp_pp1-True-True]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestOptimizerResharding::test_optimizer_resharding[src_tp_pp2-dest_tp_pp2-True-True]",
                       "tests/unit_tests/dist_checkpointing/test_optimizer.py::TestOptimizerResharding::test_optimizer_resharding[src_tp_pp3-dest_tp_pp3-True-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_retro_model.py::TestRetroModel::test_sharded_state_dict_save_load[retro-te-te]",
                       "tests/unit_tests/dist_checkpointing/models/test_retro_model.py::TestRetroModel::test_sharded_state_dict_save_load[retro-te-local]",
                       "tests/unit_tests/dist_checkpointing/models/test_retro_model.py::TestRetroModel::test_sharded_state_dict_save_load[retro-local-te]",
                       "tests/unit_tests/dist_checkpointing/models/test_retro_model.py::TestRetroModel::test_sharded_state_dict_save_load[retro-local-local]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp0-dest_tp_pp_exp0-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-True-src_tp_pp_exp1-dest_tp_pp_exp1-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp2-dest_tp_pp_exp2-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-True-src_tp_pp_exp3-dest_tp_pp_exp3-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp4-dest_tp_pp_exp4-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp5-dest_tp_pp_exp5-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-True-src_tp_pp_exp6-dest_tp_pp_exp6-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp7-dest_tp_pp_exp7-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp8-dest_tp_pp_exp8-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp9-dest_tp_pp_exp9-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp10-dest_tp_pp_exp10-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-True-src_tp_pp_exp11-dest_tp_pp_exp11-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_sequential_mlp.py::TestExpertLayerReconfiguration::test_parallel_reconfiguration_e2e[False-False-src_tp_pp_exp12-dest_tp_pp_exp12-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp0-dest_tp_pp_exp0-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[True-src_tp_pp_exp1-dest_tp_pp_exp1-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp2-dest_tp_pp_exp2-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[True-src_tp_pp_exp3-dest_tp_pp_exp3-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp4-dest_tp_pp_exp4-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp5-dest_tp_pp_exp5-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[True-src_tp_pp_exp6-dest_tp_pp_exp6-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp7-dest_tp_pp_exp7-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp8-dest_tp_pp_exp8-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp9-dest_tp_pp_exp9-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp10-dest_tp_pp_exp10-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[True-src_tp_pp_exp11-dest_tp_pp_exp11-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp12-dest_tp_pp_exp12-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[True-src_tp_pp_exp13-dest_tp_pp_exp13-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_parallel_reconfiguration_e2e[False-src_tp_pp_exp14-dest_tp_pp_exp14-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp0-dest_tp_pp_exp0-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp1-dest_tp_pp_exp1-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp2-dest_tp_pp_exp2-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp3-dest_tp_pp_exp3-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp4-dest_tp_pp_exp4-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp5-dest_tp_pp_exp5-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp6-dest_tp_pp_exp6-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp7-dest_tp_pp_exp7-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp8-dest_tp_pp_exp8-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[sequential-src_tp_pp_exp9-dest_tp_pp_exp9-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp10-dest_tp_pp_exp10-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp11-dest_tp_pp_exp11-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp12-dest_tp_pp_exp12-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp13-dest_tp_pp_exp13-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp14-dest_tp_pp_exp14-False]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp15-dest_tp_pp_exp15-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp16-dest_tp_pp_exp16-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp17-dest_tp_pp_exp17-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp18-dest_tp_pp_exp18-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_grouped_mlp.py::TestGroupedMLPReconfiguration::test_sequential_grouped_mlp_interchangeable[grouped-src_tp_pp_exp19-dest_tp_pp_exp19-True]",
                       "tests/unit_tests/dist_checkpointing/models/test_mlp_glu.py::TestParallelMLPWithGLU::test_parallel_reconfiguration_e2e[src_tp_pp0-dest_tp_pp0]",
                       "tests/unit_tests/dist_checkpointing/models/test_mlp_glu.py::TestParallelMLPWithGLU::test_parallel_reconfiguration_e2e[src_tp_pp1-dest_tp_pp1]",
                       "tests/unit_tests/dist_checkpointing/models/test_mlp_glu.py::TestParallelMLPWithGLU::test_parallel_reconfiguration_e2e[src_tp_pp2-dest_tp_pp2]",
                       "tests/unit_tests/dist_checkpointing/models/test_mlp_glu.py::TestParallelMLPWithGLU::test_parallel_reconfiguration_e2e[src_tp_pp3-dest_tp_pp3]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_partition_change_save_load[src_tp_pp0-dest_tp_pp0]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_partition_change_save_load[src_tp_pp1-dest_tp_pp1]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_partition_change_save_load[src_tp_pp2-dest_tp_pp2]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_partition_change_save_load[src_tp_pp3-dest_tp_pp3]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_reformulate_nd_flattened_tensors[src_tp_pp0-dest_tp_pp0-expected_ckpt_offsets_by_rank0]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_reformulate_nd_flattened_tensors[src_tp_pp1-dest_tp_pp1-expected_ckpt_offsets_by_rank1]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_load_tensor_metadata[src_tp_pp0]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_load_tensor_metadata[src_tp_pp1]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_load_tensor_metadata[src_tp_pp2]",
                       "tests/unit_tests/dist_checkpointing/test_flattened_resharding.py::TestFlattenedResharding::test_load_tensor_metadata[src_tp_pp3]",
                       "tests/unit_tests/inference/text_generation_controllers/test_simple_text_generation_controller.py::TestTextGenerationController::test_generate_all_output_tokens_static_batch",
                       "tests/unit_tests/inference/engines/test_mcore_engine.py::TestMCoreEngine::test_generate",
                       "tests/unit_tests/models/test_clip_vit_model.py::TestCLIPViTModel::test_forward",
                       "tests/unit_tests/models/test_gpt_model.py::TestGPTModel::test_post_process_forward",
                       "tests/unit_tests/models/test_t5_model.py::TestT5Model::test_post_process_forward",
                       "tests/unit_tests/models/test_multimodal_projector.py::TestMultimodalProjector::test_forward",
                       "tests/unit_tests/models/test_llava_model.py::TestLLaVAModel::test_forward",
                       "tests/unit_tests/models/test_bert_model.py::TestBertModel::test_post_process_forward",
                       "tests/unit_tests/pipeline_parallel/test_schedules.py::test_forward_backward_func_without_pipeline_parallel",
                       "tests/unit_tests/pipeline_parallel/test_schedules.py::test_forward_backward_func_with_pipeline_parallel",
                       "tests/unit_tests/pipeline_parallel/test_schedules.py::test_forward_backward_func_with_interleaving",
                       "tests/unit_tests/transformer/test_transformer_block.py::TestParallelTransformerBlock::test_gpu_forward",
                       "tests/unit_tests/transformer/test_transformer_block.py::TestParallelTransformerBlock::test_gpu_forward_full_checkpoint",
                       "tests/unit_tests/transformer/test_transformer_block.py::TestParallelTransformerBlock::test_gpu_forward_selective_checkpoint",
                       "tests/unit_tests/transformer/test_retro_attention.py::TestRetroAttention::test_constructor",
                       "tests/unit_tests/transformer/test_retro_attention.py::TestRetroAttention::test_gpu_forward",
                       "tests/unit_tests/transformer/test_attention.py::TestParallelAttention::test_gpu_forward",
                       "tests/unit_tests/transformer/test_attention.py::TestParallelAttention::test_fused_rope_gpu_forward",
                       "tests/unit_tests/transformer/test_attention.py::TestParallelAttention::test_checkpointed_gpu_forward",
                       "tests/unit_tests/transformer/test_transformer_layer.py::TestParallelTransformerLayer::test_gpu_forward",
                       "tests/unit_tests/transformer/test_spec_customization.py::TestSpecCustomization::test_transformer_block_custom",
                       "tests/unit_tests/transformer/moe/test_a2a_token_dispatcher.py::TestAlltoAllDispatcher::test_capacity_forward_backward[1-8]",
                       "tests/unit_tests/transformer/moe/test_a2a_token_dispatcher.py::TestAlltoAllDispatcher::test_capacity_forward_backward[8-1]",
                       "tests/unit_tests/transformer/moe/test_a2a_token_dispatcher.py::TestAlltoAllDispatcher::test_capacity_forward_backward[4-2]",
                       "tests/unit_tests/transformer/moe/test_a2a_token_dispatcher.py::TestAlltoAllDispatcher::test_capacity_forward_backward[1-1]",
                       "tests/unit_tests/transformer/moe/test_a2a_token_dispatcher.py::TestAlltoAllDispatcher::test_capacity_padding_forward_backward[1-8]",
                       "tests/unit_tests/transformer/moe/test_a2a_token_dispatcher.py::TestAlltoAllDispatcher::test_capacity_padding_forward_backward[8-1]",
                       "tests/unit_tests/transformer/moe/test_a2a_token_dispatcher.py::TestAlltoAllDispatcher::test_capacity_padding_forward_backward[4-2]",
                       "tests/unit_tests/transformer/moe/test_a2a_token_dispatcher.py::TestAlltoAllDispatcher::test_capacity_padding_forward_backward[1-1]",
                       "tests/unit_tests/data/test_preprocess_data.py::test_preprocess_data_bert",
                       "tests/unit_tests/inference/model_inference_wrappers/gpt/test_gpt_inference_wrapper.py::TestGPTInferenceWrapper::test_inference_pipeline_parallel_small_size",
                       "tests/unit_tests/inference/model_inference_wrappers/gpt/test_gpt_inference_wrapper.py::TestGPTInferenceWrapper::test_inference_pipeline_parallel_large__size",
                       "tests/unit_tests/inference/model_inference_wrappers/gpt/test_gpt_inference_wrapper.py::TestGPTInferenceWrapper::test_inference_only_tensor_parallel")

def pytest_collection_modifyitems(config, items):
    for item in items:
        if item.nodeid in list_of_skip:
            item.add_marker(pytest.mark.xfail(run=False))