repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: isort
    language: python
    additional_dependencies: ["isort==5.13.2"]
    files: ^experimental/lite/.*\.py$
  - id: black
    name: black
    entry: black
    language: python
    additional_dependencies: ["black==24.4.2"]
    files: ^experimental/lite/.*\.py$
    args: ["--skip-magic-trailing-comma", "--skip-string-normalization"]
