# Quantization module -- imported by transformer and models.
# Changes cascade through transformer.
test_buckets:
  - fp8_param
  - pipeline_parallel
  - models
  - ckpt_optimizer
  - ckpt
  - ckpt_models
  - ckpt_moe_experts
  - transformer
  - transformer_moe
  - distributed_fsdp
  - catch_all
