# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.

from megatron.training.utils.common_utils import (
    average_losses_across_data_parallel_group,
    calc_dtensor_params_l2_norm,
    calc_params_l2_norm,
    check_adlr_autoresume_termination,
    get_batch_on_this_cp_rank,
    get_batch_on_this_tp_rank,
    get_blend_and_blend_per_split,
    get_device_arch_version,
    get_ltor_masks_and_position_ids,
    get_nvtx_range,
    has_nvrx_checkpointing_async_support,
    has_nvrx_installed,
    is_first_or_last_pipeline_stage,
    is_hybrid_model,
    is_last_rank,
    is_rank0,
    logical_and_across_model_parallel_group,
    print_params_min_max_norm,
    print_rank_0,
    print_rank_last,
    reduce_max_stat_across_model_parallel_group,
    report_memory,
    to_empty_if_meta_device,
    update_use_dist_ckpt,
    warn_rank_0,
)
from megatron.training.utils.log_utils import append_to_progress_log
