# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.

from megatron.training.utils.common_utils import (
    calc_params_l2_norm,
    calc_dtensor_params_l2_norm,
    average_losses_across_data_parallel_group,
    reduce_max_stat_across_model_parallel_group,
    logical_and_across_model_parallel_group,
    report_memory,
    print_params_min_max_norm,
    check_adlr_autoresume_termination,
    get_ltor_masks_and_position_ids,
    print_rank_0,
    warn_rank_0,
    is_rank0,
    is_last_rank,
    print_rank_last,
    is_hybrid_model,
    is_first_or_last_pipeline_stage,
    get_device_arch_version,
    append_to_progress_log,
    get_blend_and_blend_per_split,
    get_batch_on_this_tp_rank,
    update_use_dist_ckpt,
    to_empty_if_meta_device,
    get_nvtx_range,
    has_nvrx_installed,
    has_nvrx_checkpointing_async_support,
)
