# Use NVIDIA's PyTorch image as the base
FROM nvcr.io/nvidia/pytorch:24.03-py3

# Set the working directory in the container
WORKDIR /workspace

# Copy the requirements file into the container at /app
COPY requirements.txt /workspace

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install additional Python packages
RUN pip install pip install git+https://github.com/fanshiqing/grouped_gemm@v1.0