- agent_type: examples.rl.environments.countdown.countdown_agent.CountdownAgent
  agent_args:
    hf_dataset_name: "Jiayi-Pan/Countdown-Tasks-3to4"
    split: "train"
  weight: 1.0
- agent_type: examples.rl.environments.math.openmath_agent.OpenMathInstructAgent
  agent_args: {}
  weight: 1.0
