# Dist checkpointing module (serialization, mapping, strategies).
#
# Test imports traced:
#   ckpt*           → dist_checkpointing.* (heavily, all sub-buckets)
#   transformer*    → dist_checkpointing.mapping (ShardedObject, ShardedTensor)
#   post_training   → dist_checkpointing
test_buckets:
  - ckpt
  - ckpt_optimizer
  - ckpt_models
  - ckpt_moe_experts
  - transformer
  - transformer_moe
  - post_training
