name: python

on:
  workflow_dispatch:
  pull_request:
    branches:
      '**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    strategy:
      matrix:
        pyVersion: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false

    runs-on: ubuntu-22.04
    container:
      image: deepspeed/gh-builder:py${{ matrix.pyVersion }}

    steps:
      - uses: actions/checkout@v4

      - name: environment
        run: |
          which python
          python --version
      - name: Install Megatron-DeepSpeed
        run: |
          pip3 install .
