# Pipeline parallel module -- imported by transformer, models, datasets
# (hybrid_cp_schedule).  Affects nearly all test buckets except model_configs.
test_buckets:
  - fp8_param
  - pipeline_parallel
  - models
  - data
  - ckpt_optimizer
  - ckpt
  - ckpt_models
  - ckpt_moe_experts
  - transformer
  - transformer_moe
  - distributed_fsdp
  - catch_all
